name: Jetson image

on:
  push:
    paths:
      - 'Dockerfile-minimal.rosjetson'
      - 'ros_entrypoint.sh'
      - 'src/**'

jobs:
  jetson-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          file: ./Dockerfile-minimal.rosjetson
          push: true
          build-args: |
            ZED_SDK_MAJOR=3
            ZED_SDK_MINOR=7
            L4T_MAJOR_VERSION=35
            L4T_MINOR_VERSION=1
            ROS_DISTRO_ARG=noetic
          tags: jagamatrix/zed2-docker:jetson-minimal
          cache-from: type=registry,ref=jagamatrix/zed2-docker:buildcache-jetson-minimal
          cache-to: type=registry,ref=jagamatrix/zed2-docker:buildcache-jetson-minimal,mode=max
